name: ybey_app
description: A Flutter app for YBEY - You Become Yourself

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  url_launcher: ^6.1.10
  http: ^0.13.6
  flutter_tts: ^4.0.0
  audioplayers: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/founder.png
    - assets/images/founder.jpeg
    - assets/images/founder.jpg
    - assets/1000033106.jpeg
    - assets/audio/welcome.mp3
    - assets/audio/welcome.mpeg
